name: friends
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
#to lunch url naively or in browser
  url_launcher: ^6.1.5
#to use media query in easiest way
  responsive_s: ^1.1.1
#to details with svg images
  flutter_svg: ^1.1.4
#state management package
  bloc: ^8.1.0
#to store all data in local storage
  shared_preferences: ^2.0.15
#to check network connection
  internet_connection_checker: ^0.0.1+4
#value equality
  equatable: ^2.0.5
#that package contain a lot of build-in functions
#that used in dart and flutter
  dartz:
#firebase  packages
  firebase_auth: ^3.7.0
  firebase_core: ^1.21.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
#all assets in app
  assets:
    - assets/images/
    - assets/fonts/