name: friends
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
#navigation bar
  curved_navigation_bar: ^1.0.3
#for getting device id
  device_info_plus: ^4.1.2
#for animation icons
  lottie: ^1.4.2
#dependency injection package
  get_it: ^7.2.0
#to lunch url naively or in browser
  url_launcher: ^6.1.5
#to use media query in easiest way
  responsive_s: ^1.1.1
#to details with svg images
  flutter_svg: ^1.1.4
#state management package
  bloc: ^8.1.0
#helper package for bloc
  flutter_bloc: ^8.1.1
#to store all data in local storage
  shared_preferences: ^2.0.15
#to check network connection
  internet_connection_checker: ^0.0.1+4
#value equality
  equatable: ^2.0.5
#that package contain a lot of build-in functions
#that used in dart and flutter
  dartz:
#firebase  packages
  firebase_auth: ^3.7.0
  firebase_core: ^1.21.1
  firebase_database: ^9.1.4
  flutter_facebook_auth: ^4.4.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
#all assets in app
  assets:
    - assets/images/
    - assets/lottie/
  fonts:
    - family: firaCode
      fonts:
        - asset: assets/fonts/firacode/FiraCode-Bold.ttf
          weight: 700
        - asset: assets/fonts/firacode/FiraCode-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/firacode/FiraCode-Light.ttf
          weight: 300
        - asset: assets/fonts/firacode/FiraCode-Medium.ttf
          weight: 500
        - asset: assets/fonts/firacode/FiraCode-Regular.ttf
          weight: 400
    - family: roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 800
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Italic.ttf
    - family: MyFlutterApp
      fonts:
        - asset: assets/icons/fonts/MyFlutterApp.ttf
