name: friends
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
#to check network connection
  data_connection_checker: ^0.3.4
#value equality
  equatable:
#that package contain a lot of build-in functions
#that used in dart and flutter
  dartz:
#firebase  packages
  firebase_auth:
  firebase_core:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true