/// Flutter icons MyFlutterApp
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  static const IconData user = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData open_lock = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_65 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_material_mood = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_material_delete_sweep = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_32 = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_metro_qrcode = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_awesome_home = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_ionic_md_notifications_outline = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData af89ce777b47408d7672a330740a3b74 = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
